version: "3.8"

services:
  webapp:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - MONGODB_DB=sentiment_analysis

  ml-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - MONGODB_DB=sentiment_analysis

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sentiment_analysis
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: