version: "3.8"

services:
  webapp:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  ml-client:
    build:
      context: ./machine-learning-client
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sentiment_analysis
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: