name: Web App Lint
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web_app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv sync --dev --python $(which python)
          pipenv run pip list  # add this line temporarily to verify installed versions
    
      - name: Lint with pylint
        if: ${{ hashFiles('web_app/**/*.py') != '' }}
        run: |
          pipenv run pylint **/*.py

      - name: Format with black
        if: ${{ hashFiles('web_app/**/*.py') != '' }}
        run: |
          pipenv run black --diff --check .
