name: ML Unit Tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: machine_learning_client

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install --dev
          python -m pipenv install pytest
          pipenv install werkzeug

      - name: Run pytest
        run: pipenv run pytest
        working-directory: machine_learning_client
