name: Web App Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web_app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: web_app
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install --dev
          python -m pipenv install pymongo 
          pipenv run pip install requests 
          pipenv run pip install flask
          pipenv run pip install pytest pytest-cov

      - name: Run pytest
        working-directory: web_app
        run: |
            pipenv run pytest --cov=web_app --cov-config=.coveragerc 

